"""Observation-family protocol for location likelihoods and derivatives."""
from typing import Protocol, runtime_checkable

@runtime_checkable
class ObservationFamily(Protocol):
    name: str
    scale: object
    gaussian_location: bool
    def logpdf(self, y, eta, params): ...
    def cdf(self, y, eta, params): ...
    def sf(self, y, eta, params): ...
    def ppf(self, p, eta, params): ...
    def grad_eta(self, y, eta, params): ...
    def hess_eta(self, y, eta, params): ...
